name: go release

on:
  release:
    types: [created]

jobs:
  build_bp3ui:
    permissions:
      contents: write
    uses: bavix/.github/.github/workflows/go-release-binary.yml@0.0.2
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
